### ISSUE TITLE
Error when  training the model

### ISSUE THREAD

**Issue by jwxsp1** [facebookresearch/dpr-scale#10]
Hi, when I try to train the model, I have an error:
![image](https://user-images.githubusercontent.com/115166051/221403840-e8edb04b-d3fb-4f5e-bcb0-1db6ca95691c.png)
Do you know how to fix it?

**Comment by ccsasuke** [comment]
Hi @jwxsp1, as the error message mentioned, you're using the [slurm trainer](https://github.com/facebookresearch/dpr-scale/blob/main/dpr_scale/conf/trainer/slurm_aws.yaml), which will produce an error if SLURM is not found. If your cluster does not use slurm, you should change to a different trainer such as `gpu_1_host`.

**Comment by jwxsp1** [comment]
Hello, thank you for your reply. I have tried to change the trainer, but it seems that there is an error in the way I make the change. Could you tell me how to change the trainer? Thank you for your help

**Comment by jwxsp1** [comment]
> Hi @jwxsp1, as the error message mentioned, you're using the [slurm trainer](https://github.com/facebookresearch/dpr-scale/blob/main/dpr_scale/conf/trainer/slurm_aws.yaml), which will produce an error if SLURM is not found. If your cluster does not use slurm, you should change to a different trainer such as `gpu_1_host`.

Hi, thank you for your reply. I have tried to change the trainer, but it seems that there is an error in the way I make the change. Could you tell me how to change the trainer? Thank you for your help

**Comment by jwxsp1** [comment]
> Hi @jwxsp1, as the error message mentioned, you're using the [slurm trainer](https://github.com/facebookresearch/dpr-scale/blob/main/dpr_scale/conf/trainer/slurm_aws.yaml), which will produce an error if SLURM is not found. If your cluster does not use slurm, you should change to a different trainer such as `gpu_1_host`.

Hello, thank you for your reply. I have tried to replace the trainer, but there seems to be a new problem. How can I solve this problem? I would appreciate it if you would like to answer it.
![image](https://user-images.githubusercontent.com/115166051/221632298-de3cf69f-5410-4c14-b878-186daf9c2db2.png)

**Comment by ccsasuke** [comment]
@jwxsp1 This [line](https://github.com/facebookresearch/dpr-scale/blob/a761800a4c51644c8a633b16f3139972e205f7cd/dpr_scale/conf/config.py#L23) in the default config is supposed to address this error. Are you loading the configs correctly? Our project uses [Hydra](https://hydra.cc/docs/intro/) to manage configs and command-line arguments in case you'd like to learn more about how to change configs such as the `trainer`.
