### ISSUE TITLE
Reddit data download link broken

### ISSUE THREAD

**Issue by jordane95** [facebookresearch/dpr-scale#11]
Hi, I'm trying to download the 200M reddit data. But it seems that the url is broken

```
$wget https://dl.fbaipublicfiles.com/dpr_scale/reddit/train.200M.jsonl
--2023-04-18 15:05:43--  https://dl.fbaipublicfiles.com/dpr_scale/reddit/train.200M.jsonl
Resolving dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)... 13.32.50.61, 13.32.50.10, 13.32.50.72, ...
Connecting to dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)|13.32.50.61|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-04-18 15:05:44 ERROR 403: Forbidden.
```

**Comment by ccsasuke** [comment]
Hi @jordane95, upon checking, unfortunately this data has been purged. I can try to recover it, but this is difficult and often impossible. I'll update here if have any luck retrieving this file.

**Comment by jordane95** [comment]
Thanks for your effort! Btw, do you still have the reddit data preprocessing script? That's another way for reproduction

**Comment by ccsasuke** [comment]
@jordane95 The link has been fixed, sorry for the inconvenience.
