### ISSUE TITLE
Some questions about 'generating training queries'

### ISSUE THREAD

**Issue by jjonhwa** [facebookresearch/dpr-scale#2]
To generate our own training data for Lambda, we want to create training queries. At this time, I have a question about the code in 'dpr_scale/utils/prep_wiki_exp.py'.

![image](https://user-images.githubusercontent.com/53552847/174227276-8ddeada0-558f-4353-a9fd-e1f126a62df1.png)
Looking at the code above, it can be seen that the query is obtained from `passage_sents`.

![image](https://user-images.githubusercontent.com/53552847/174227355-e4d850e5-d7c9-46c9-ba44-290b2dbf5928.png)
However, if you look at the source of `passage_sents`, you can see that it was taken from the document. Am I right to understand?

![image](https://user-images.githubusercontent.com/53552847/174228584-1704c8c0-3a05-4f7e-8731-fb7bbeaac0fb.png)
In the end, it seems that `positive_ctxs` stores the passage from `passage_sents`, and I wonder if query and context are used correctly.

If you have time, please reply. Thank you.

**Comment by ccsasuke** [comment]
Hi @jjonhwa, thanks for your interest in our work.

As stated in the paper, the training of the Lexical Model is as follows:
Query: a random sentence from Wikipedia.
Positive Context: The passage where the query comes from.

Therefore, both the queries and contexts come from the "documents" in this case. Does that answer your question?

**Comment by jjonhwa** [comment]
I see. I'm sorry that I missed that part.
Thanks to your detailed explanation, I understood exactly.

Thank you for your reply.
